name: publish

on:
  pubsh:
    tags:
      - v*

jobs:
  publish:
    name: Publish VSCode Extension
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          npm ci
          npm install -g vsce
      - run: vsce publish -p ${{ secrets.VSCODE_EXTENSION_TOKEN }}